---
# Install/configure everything related to web browsers

# Firefox
- name: "Browsers: firefox: remove from distro"
  become: yes
  apt:
    name=firefox
    state=absent

- name: "Browsers: firefox: download version 34"
  shell:
    wget http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt/pool/main/f/firefox-mozilla-build/firefox-mozilla-build_34.0.5-0ubuntu1_amd64.deb?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fubuntuzilla%2Ffiles%2Fmozilla%2Fapt%2Fpool%2Fmain%2Ff%2Ffirefox-mozilla-build%2Ffirefox-mozilla-build_34.0.5-0ubuntu1_amd64.deb
    chdir=/tmp/

- name: "Browsers: firefox: install"
  become: yes
  apt:
    deb=/tmp/firefox-mozilla-build_34.0.5-0ubuntu1_amd64.deb\?r\=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fubuntuzilla%2Ffiles%2Fmozilla%2Fapt%2Fpool%2Fmain%2Ff%2Ffirefox-mozilla-build%2Ffirefox-mozilla-build_34.0.5-0ubuntu1_amd64.deb


# PhantomJS
- name: "Browsers: install PhantomJS"
  become: yes
  apt:
    name=phantomjs
    state=present
