---
# Install/configure everything related to web browsers

# Firefox
- name: "Browsers: firefox: remove from distro"
  become: yes
  apt:
    name=firefox
    state=absent

- name: "Browsers: firefox: install system dependencies"
  apt:
    pkg=firefox
    state=build-dep

- name: "Browsers: firefox: download"
  get_url:
    url="https://sourceforge.net/projects/ubuntuzilla/files/mozilla/apt/pool/main/f/firefox-mozilla-build/{{ firefox_file_name }}"
    dest=/tmp
    checksum="sha512:{{ firefox_checksum }}"

- name: "Browsers: firefox: install"
  become: yes
  apt:
    deb="/tmp/{{ firefox_file_name }}"

# PhantomJS
- name: "Browsers: install PhantomJS"
  become: yes
  apt:
    name=phantomjs
    state=present
