---

- name: "JS: install yarn public key (apt)"
  apt_key:
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present

- name: "JS: add yarn apt repository"
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: "JS: apt update"
  become: yes
  apt:
    upgrade=dist
    update_cache=yes

- name: "JS: install yarn and nodejs"
  become: yes
  apt:
    name={{item}}
    state=present
  with_items:
    - yarn
    - nodejs

- name: "JS: add node as an alternative to nodejs"
  alternatives:
    name: node
    path: /usr/bin/nodejs
    link: /usr/bin/node
