---

- name: "system: update"
  become: yes
  apt:
    upgrade=dist
    update_cache=yes

- name: "system: install dependencies"
  become: yes
  apt:
    name={{item}}
    state=present
  with_items:
    # Java is needed in order to connect the Jenkins slaves to the master
    - openjdk-8-jre
    # Basics
    - build-essential
    - htop
    - curl
    # Time
    - ntp
    # VCS
    - git-core
    # Keep /tmp folder clean
    - tmpreaper
    # Robot Framework dependencies
    - xvfb
    - x11-apps
    - xfonts-100dpi
    - xfonts-75dpi
    - xfonts-scalable
    - xfonts-cyrillic
    # Others
    - imagemagick
    - ufw
    - fail2ban
    - unattended-upgrades

- name: "system: remove packages"
  become: yes
  apt:
    name={{item}}
    state=absent
  with_items:
    - python-software-properties
    - python-apt
    - libjpeg62-dev

# Set Timezone to US/Pacific (default was: 'Etc/UTC')
# XXX: Only a single test requires this in plone.app.form 2.2.x
# https://github.com/plone/plone.app.form/blob/2.2.x/plone/app/form/widgets/datecomponents.txt
- name: "system: set timezone to US/Pacific"
  become: yes
  copy:
    content='US/Pacific'
    dest=/etc/timezone
    owner=root
    group=root
    mode=0644
    backup=yes

- name: "system: update timezone"
  become: yes
  command:
    dpkg-reconfigure --frontend noninteractive tzdata

# UFW
- name: "system: set UFW to deny all"
  become: yes
  ufw:
    state=enabled
    policy=deny

- name: "system: set UFW to allow OpenSSH"
  become: yes
  ufw:
    rule=allow
    name=OpenSSH

- name: "system: set UFW to allow Port 80"
  become: yes
  ufw:
    rule=allow
    port=80
    proto=tcp

- name: "system: set UFW to allow Port 443"
  become: yes
  ufw:
    rule=allow
    port=443
    proto=tcp

- name: "system: set UFW to allow port 4949 from munin master"
  become: yes
  ufw:
    rule=allow
    src=162.209.104.107
    proto=tcp
    port=4949

# fail2ban
- name: "system: upload fail2ban jail.local"
  become: yes
  copy:
    src=jail.local
    dest=/etc/fail2ban/jail.local
    mode=0644
  notify: restart fail2ban

# unattended-upgrades
- name: "system: configure unattended-upgrades"
  become: yes
  copy:
    src=10periodic
    dest=/etc/apt/apt.conf.d/10periodic
    owner=root
    group=root
    mode=0644

- name: "system: upload unattended-upgrades configuration"
  become: yes
  copy:
    src=50unattended-upgrades
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    owner=root
    group=root
    mode=0644
  notify: restart unattended-upgrades

# tmpreaper
- name: "system: configure tmpreaper"
  become: yes
  lineinfile:
    dest=/etc/tmpreaper.conf
    regexp=^TMPREAPER_TIME=
    line=TMPREAPER_TIME=24
